### ISSUE TITLE
Release the project under an open-source license

### ISSUE THREAD

**Issue by EventideGlow** [hjacobs/gnucash-qif-import#5]
@hjacobs, have you considered releasing this project under a [known open-source license](http://choosealicense.com/)? I'd find it helpful to have one of them attached to this project to clarify where you stand on building upon or modifying your work here.

**Comment by hjacobs** [comment]
@Feld0 yes, you are right, will do :smile:

**Comment by EventideGlow** [comment]
@hjacobs Bump? Any update on this?

**Comment by hjacobs** [comment]
done: https://github.com/hjacobs/gnucash-qif-import/blob/master/LICENSE

**Comment by EventideGlow** [comment]
Awesome. I appreciate it!
